spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musics
    password: 123456
    username: root


flyway:
  url: jdbc:mysql://localhost:3306/musics
  schemas: USERSERVICE
  user: root
  password: 123456