

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musics?serverTimezone=UTC
    password: 123456
    username: root
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /api
